import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";

import Header from "./components/widgets/Header";
import Footer from "./components/widgets/Footer";

const worksans = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={worksans.className}>
        <Header />
        <div className="container mx-auto">
        {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
